version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    
    steps:
      - checkout
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O installer.sh
      - bash installer.sh
