version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    
    steps:
      - checkout
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O installer.sh
      - run: bash installer.sh -b -p $HOME/miniconda3
      - run: export PATH="$HOME/miniconda3/bin:$PATH"
      # Setup .condarc file.
      - run: |
          echo "channels:" > $HOME/.condarc
      - run: |
          echo "  - bioconda" >> $HOME/.condarc
      - run: |
          echo "  - conda-forge" >> $HOME/.condarc
      - run: |
          echo "  - defaults" >> $HOME/.condarc
      - run: |
          echo "always_yes: true" >> $HOME/.condarc
