version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    
    steps:
      - checkout
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O installer.sh
      - run: bash installer.sh -b -p $HOME/miniconda3
      - run: PATH="$HOME/miniconda3/bin:$PATH"
      - run: ls $HOME/miniconda3/bin
      - run: echo $PATH
      # Setup .condarc file.
      - run: |
          echo "channels:" > $HOME/.condarc;
          echo "  - bioconda" >> $HOME/.condarc;
          echo "  - conda-forge" >> $HOME/.condarc;
          echo "  - defaults" >> $HOME/.condarc;
          echo "always_yes: true" >> $HOME/.condarc;
          cat $HOME/.condarc;  # Show me!
      # Install tools for test.
      - run: conda install kallisto bwa fastqc
